version: 3


tasks:
  default:
    deps: [test, build_docs]

  devbuild:
    desc: "Rebuild shared library (if cython files have changed) and reinstall."
    deps: [lint]
    run: once
    sources:
      - src/starlord/*.pyx
      - src/starlord/*.pxd
    generates:
      - src/starlord/*.so
    cmds:
      - rm -rf build starlord.egg-info src/starlord/*.so
      - rm -rf docs/build/html/
      - pip uninstall starlord --yes
      - pip install -e .[develop]

  lint:
    desc: "Run flake8 linter"
    run: once
    cmds:
      - flake8 . --count --show-source --statistics

  test:
    deps: [lint, devbuild]
    desc: "Run pytest with coverage"
    cmds:
      - pytest --cov=starlord

  experiment:
    deps: [devbuild]
    desc: "Build and run experiment.py file for live tests."
    cmds:
      - python experiment.py

  build_docs:
    deps: [devbuild, lint]
    desc: "Build the Starlord documentation with Sphinx."
    sources:
      - src/starlord/*.py
      - src/starlord/*.pyx
      - src/starlord/*.pxd
      - docs/*.rst
      - docs/*/*.rst
      - docs/*/*.py
      - docs/*/*.toml
      - docs/conf.py
    generates:
      - docs/build/html/index.html
    cmds:
      - sphinx-build docs/ docs/build/html/
