[model]
# There are two stars in the system, so we need to interpolate the MIST grid twice.
multiplicity.mist2 = 2
# All photometry is blended, so use "--blend" instead of "--1" or "--2"
mist2.Gaia_G_DR3--blend = [10.0955, 0.0039]
mist2.GALEX_NUV--blend = [15.8431, 0.05310]
mist2.SkyMapper_u--blend = [12.0033, 0.0325]
mist2.SkyMapper_g--blend = [10.2842, 0.0477]
mist2.SkyMapper_r--blend = [9.9401, 0.0718]
mist2.SkyMapper_i--blend = [9.5456, 0.0669]
mist2.SkyMapper_z--blend = [9.52800, 0.1022]
mist2.TWOMASS_J--blend = [8.7659, 0.0320]
mist2.TWOMASS_H--blend = [8.3739, 0.0430]
mist2.WISE_W1--blend = [8.5299, 0.0504]
mist2.WISE_W2--blend = [8.5699, 0.0502]

# For unassociated stars these would normally be different, but our example case isn't
# actually unassociated so they're still the same here.
mist2.parallax--1 = [9.508, 0.018]
mist2.parallax--2 = [9.508, 0.018]

# Require the second star to be of lower mass (to disambiguate the indices)
var.mass_difference = ["p.log_mass0--1 - p.log_mass0--2", "uniform", 0, 10]

# Fix [alpha/iron] to zero
override.mist2.afe = "0"

# Instruct Starlord to use separate distances and properties
override.mist2.Av = "p.Av--i"
override.mist2.feh = "p.feh--i"
override.mist2InvAge.log_age = "p.log_age--i"
override.mist2.distance = "p.distance--i"

# All parameters are unshared
prior.Av--1 = ["trunc_normal", 0.02687, 0.03, 0, 20]
prior.Av--2 = ["trunc_normal", 0.02687, 0.03, 0, 20]
prior.distance--1 = ["trunc_power", -2, 10, 200]
prior.distance--2 = ["trunc_power", -2, 10, 200]
prior.feh--1 = ["casagrande_disk"]
prior.feh--2 = ["casagrande_disk"]
prior.log_age--1 = ["uniform", -1.5, 1.2]
prior.log_age--2 = ["uniform", -1.5, 1.2]
prior.log_mass0--1 = ["chabrier_disk"]
prior.log_mass0--2 = ["chabrier_disk"]

# Outputs to calculate
outputs = ["g.mist2.log_radius--1", "g.mist2.log_g--1", "g.mist2.log_lum--1", "g.mist2.log_teff--1",
           "g.mist2.log_radius--2", "g.mist2.log_g--2", "g.mist2.log_lum--2", "g.mist2.log_teff--2"]

[sampling]
emcee_init.burn_in = 2000
emcee_run.nsteps = 5000
emcee_init.thin = 10

[output]
terminal=true
file="wasp77.npz"
