import math
import os
import re
import sys

import cython
import numpy as np
from pytest import approx
from scipy import stats

from starlord import CodeGenerator
from starlord._config import __version__, _load_config, config


def test_expressions():
    g = CodeGenerator()
    g.expression("l.foo = np.sin(p.stuff)")
    assert len(g._like_components) == 1
    comp = g._like_components[0]
    # Check variable processing
    assert comp.requires == {"p.stuff"}
    assert comp.provides == {"l.foo"}
    assert comp.code.count("np.") == 1
    assert comp.code.count("l__foo") == 1
    assert comp.code.count("l.foo") == 0
    assert comp.code.count("p__stuff") == 1
    assert comp.code.count("p.stuff") == 0
    # Check variable aggregation
    assert g.variables is not None
    assert g.params == ("p.stuff",)
    assert g.locals == ("l.foo",)
    assert g.constants == ()
    # Check summary function
    s = g.summary().splitlines()
    assert s[1].startswith("Params:")
    assert "stuff" in s[1]
    assert s[2].startswith("Locals:")
    assert "foo" in s[2]
    # No prior was specified
    assert "Prior" in s[-1]


def test_compilation():
    code = "# Generated by Starlord.  Versions:\n"
    versions = f"# Starlord {__version__}, Cython {cython.__version__}, Python {sys.version}"
    code += (re.sub("\n", " ", versions))
    code += "\nfrom libc cimport math\n\n"
    code += "cpdef double testFunction(double x):\n"
    code += "    return 3.5 * math.sin(x/2.)\n"
    hash = CodeGenerator._compile_to_module(code)
    mod = CodeGenerator._load_module(hash)
    assert mod.testFunction(12.) == approx(3.5 * math.sin(12. / 2.))


def test_model():
    g = CodeGenerator()
    g.constraint('p.bar', 'uniform', ['c.min_bar', 'c.max_bar'])
    g.constraint('p.foo', 'normal', ['c.mean_foo', 'c.std_foo'])
    g.prior('p.bar', 'uniform', [-10.0, 10.0])
    g.prior('p.foo', 'uniform', [-10.0, 10.0])
    g.optional_likelihood_terms = True
    module = g.compile()
    model = module.Model(mean_foo=2.0, std_foo=1.0, min_bar=3, max_bar=8)
    print(model.code[0])
    assert model.param_names == ['bar', 'foo']
    assert model.const_names == ['max_bar', 'mean_foo', 'min_bar', 'std_foo']
    assert model.c__mean_foo == 2
    assert model.c__std_foo == 1.0
    assert model.c__min_bar == 3.0
    assert model.c__max_bar == 8.0
    for xt in np.random.rand(100, 2):
        xt[0] += 3.5
        expect = -np.log(8. - 3.) + stats.norm.logpdf(xt[1], 2.0, 1.0)
        assert model.log_like(xt) == approx(expect, rel=1e-9)
        assert model.log_prior(xt) == approx(-2 * np.log(20), rel=1e-9)
    model.c__std_foo = np.nan
    for xt in np.random.rand(100, 2):
        xt[0] += 3.5
        assert model.log_like(xt) == approx(-np.log(8. - 3.), rel=1e-9)
        assert model.log_prior(xt) == approx(-2 * np.log(20), rel=1e-9)


def test_config():
    _load_config()
    assert config.system in ["Windows", "Linux", "Darwin"]
    assert os.path.exists(config.cache_dir)
    assert os.path.exists(config.grid_dir)
